# Generated by Django 5.1.4 on 2025-01-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('user', '0002_user_is_verified')]

    operations = [migrations.AlterField(model_name='user', name='is_verified', field=models.BooleanField(default=True))]
